version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: esperion-uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - "3001:3001"
    environment:
      - UPTIME_KUMA_PORT=3001
    restart: unless-stopped
    networks:
      - esperion-network

volumes:
  uptime-kuma-data:
    name: esperion-uptime-kuma-data

networks:
  esperion-network:
    external: true
