// Generated by nuxt-security
import type { HookResult } from '@nuxt/schema'
import type { ModuleOptions, BasicAuth } from 'nuxt-security'

declare module 'nuxt/schema' {
  interface NuxtOptions {
    security: ModuleOptions
  }
  interface RuntimeConfig {
    security: ModuleOptions,
    private: { basicAuth: BasicAuth | false, [key: string]: any }
  }
  interface NuxtHooks {
    'nuxt-security:prerenderedHeaders': (prerenderedHeaders: Record<string, Record<string, string>>) => HookResult
  }
}

export {}
